#! /bin/zsh

#
# Copyright (c) 2024 Dev Bwaim team
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#

source "config/toolbox.sh"

version=0.4.12
hook="Pre-commit check"
progress "$hook"

if [ ! -z "$stagedKotlinFiles" ]; then

    stashTmpChanges

    #run autoformatter
    progress "Autoreformatting the code..."

    ktlint -F -R config/rules/ktlint-compose-$version-all.jar --baseline=config/baseline/baseline-ktlint.xml "\!**/copyright.kt" $stagedKotlinFiles
    if [ $? -eq 0 ]; then
        printSuccess "Autoreformatting done"
        # we added changes if success (you can also add them in the autoformatting step)
        git add $stagedKotlinFiles
    else
        showFailureNotification "Autoreformatter" "failed: $?"
        unStashTmpChanges
        exitWithMessage "Ktlint failed"
    fi

    #Run linter
    progress "Detekt lint in progress..."

    # Convert newline-separated list to comma-separated list
    working_files=$(echo "$stagedKotlinFiles" | tr '\n' ',')

    # Remove trailing comma
    working_files=${working_files%,}

    detekt -p config/rules/detekt-compose-$version-all.jar -c config/detekt/detekt.yml --baseline config/baseline/baseline.xml -i $working_files
    if [ $? -eq 0 ]; then
        printSuccess "Linting done"
    else
        showFailureNotification "Detekt failed" "failed: $?"
        unStashTmpChanges
        exitWithMessage "Detekt failed"
    fi
    #You can also git add . if you linter autocorrect

    showSuccessNotification "Code sanitized with success"
else
    printWarning "No kotlin files staged, checks skipped"
fi