#!/bin/sh

source "config/toolbox.sh"

command -v git-lfs >/dev/null 2>&1 || { echo >&2 "\nThis repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'pre-push' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks').\n"; exit 2; }
git lfs pre-push "$@"

#Run Androidlinter
progress "AndroidLint in progress..."
./gradlew lint #implies that you define lint {} in your build{.gradle|.kts}
if [ $? -eq 0 ]; then
    printSuccess "AndroidLint done"
else
    showFailureNotification "AndroidLint failed" "failed: $?"
    exitWithMessage "AndroidLint failed"
fi

showSuccessNotification "Code sanitized with success"