#!/bin/bash

echo "Git hook pre commit spotless"

cd "$(git rev-parse --show-toplevel)"

#./gradlew spotlessApply
#STATUS=$?
## return 1 exit code if running checks fails
#[ $STATUS -ne 0 ] && exit 1

./gradlew --init-script gradle/init.gradle.kts --no-configuration-cache spotlessCheck
STATUS=$?

if [ $STATUS -ne 0 ]
then
  ./gradlew --init-script gradle/init.gradle.kts spotlessApply
fi

# return 1 exit code if running checks fails
[ $STATUS -ne 0 ] && exit 1

exit 0
